version: '3.8'

services:
  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgresql_volume:/var/lib/postgresql/data/:rw
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h ${POSTGRES_HOST} -p ${POSTGRES_PORT} -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    image: expext/yamdb_final:latest
    restart: always
    volumes:
      - static_value:/app/static/:rw
      - media_value:/app/media/:rw
    ports:
     - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./.env

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - static_value:/app/static/:rw
      - media_value:/app/media/:rw
    depends_on:
      - web

volumes:
  postgresql_volume:
  static_value:
  media_value:
